---
language: python
python: "3.6"
before_install:
  - |
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -q tokens/ || {
      echo "No updates to token files, skipping build."
      exit
    }
install:
  - pip install yamllint
  - pip install -r scripts/requirements.txt
cache: pip

script:
  - git diff --name-only $TRAVIS_COMMIT_RANGE | grep tokens/
  - git diff --name-only $TRAVIS_COMMIT_RANGE | grep tokens/ | xargs python scripts/test.py
  - git diff --name-only $TRAVIS_COMMIT_RANGE | grep tokens/ | xargs yamllint -c .yamllint
  
 # Ignore NuGet Packages
*.nupkg

# Ignore the NuGet packages folder in the root of the repository. If needed, prefix 'packages'
# with additional folder names if it's not in the same folder as .tfignore.   
packages

# Exclude package target files which may be required for MSBuild, again prefixing the folder name as needed.
!packages/*.targets

# Omit temporary files
project.lock.json
project.assets.json
*.nuget.props
